is_key_held = False
fig = None
default_title = "Hold CTRL to make a selection"
ls = []
images_drawn = []
current_image_slider = 0
median_images = []
results = []
starting_coordinates = (0, 0)
flood_fill_tolerance = 0.2
dataset_path = None
